name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - "Cargo.toml"
      - "src/**"
      - ".github/workflows/rust.yml"
  pull_request:
    branches: [ "main" ]
    paths:
          - "Cargo.toml"
          - "src/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal --no-self-update
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build WebAssembly
      run: |
        wasm-pack build --target web --out-dir pkg
    - name: Upload WebAssembly package
      uses: actions/upload-artifact@v4
      with:
        name: wasm-package
        path: pkg